#!/bin/bash
# The `bash HOWTO` command given at the command line within the `mdgBookSVG6Kit-main` directory
# in your computer will automatically carry out the following steps leading to the creation of the 
# collection book: `mdgBookSVG6v1.pdf`.
# 
# Create three sub-folders: `bin`, `images`, `res`, under the `mdgBookSVG-main` directory
#		`bin` - folder for Bash files: mdg62mid+svg.sh, mdg62midRndN+svg.sh, mdgEntriesSVGgg2.sh
#		`images` - folder for image files for book cover/title page: 1ed.png, FrontCover.pdf
#		`res` - folder for ABC, SVG, PDF output files; should initially contain: 
#			sd-TAB.pdf - table of measure numbers
#			gerlach-schottische.abc - table of measures 
#			hyperref.cfg - file containing the \hypersetup{} keyvalues for the \hyperref pkg
#			mdg6.bib - bibliography file for the book
#			mdgBookSVG6v1.tex - main LaTeX file for book 
#			mdgBookSVG6v1-cover.tex - LaTeX file for cover page

	mkdir bin images res
	mv *.sh bin
	mv 1ed.png images; mv FrontCover.pdf images 
	mv sd-TAB.pdf res; mv gerlach-schottische.abc res
	mv *.tex res; mv hyperref.cfg res; mv mdg6.bib res

# Change directory res folder then, for each  Bash file in `bin`, create a link 
# from `bib` to `res`
	
	cd res 
	ln -s ../bin/*.sh . 

# Within `res` directory, generate nnn MDGs (nnn is number of MDG SDs in book to be created)
# For 25 SDs to be generated: nnn=025. Here we create 20. 

	./mdg62midRndN+svg.sh 020

# Generate a list of SVGs created by the previous step:

	ls --color=never ggst-*.svg > svgList.txt

# Create a list of figure entries for LaTeX file; *.pdf_tex files are also created using inkscape

	./mdgEntriesSVGgg2.sh svgList.txt

# Change the font sizes of titles, subtitles. etc. in each ggst-*.pdf_tex file

	sed -i 's/\\textbf{ggst/\\textbf{\\footnotesize \\tt ggst/g' ggst-*.pdf_tex
	sed -i 's/\\textbf{Perm\./\\textbf{\\footnotesize \\tt Perm\.\\/g' ggst-*.pdf_tex
	sed -i 's/\\textbf{= 70/\\textbf{\\footnotesize = 70/g' ggst-*.pdf_tex
	sed -i 's/\\textbf{= 80/\\textbf{\\footnotesize = 80/g' ggst-*.pdf_tex
	sed -i 's/⠀⠀⠀⠀⠀Fine/ \\scriptsize\\tt \\hspace{0\.075in}Fine/g' ggst-*.pdf_tex
	sed -i 's/D\.C\. al Fine/\\scriptsize\\tt D\.C\. al Fine/g' ggst-*.pdf_tex
	sed -i 's/(no repeats)/\\scriptsize\\tt (no repeats)/g' ggst-*.pdf_tex

# Move svgList.txt.output to svgList.tex

	cp svgList.txt.output svgList.tex

# Remove trailing `001` from each svgList.tex entry 

	sed -i.OLD 's/001}/}/g' svgList.tex
	sed -i.OLD 's/001.mid}/.mid}/g' svgList.tex

# Create the gerlach-schottisches.pdf (table of measures) SVGs; also *pdf_tex files using inkscape

	abcm2ps -v -O= gerlach-schottische.abc
	inkscape --export-filename=gerlach-schottische001.pdf --export-area-drawing --export-latex --export-latex gerlach-schottische001.svg 
	inkscape --export-filename=gerlach-schottische002.pdf --export-area-drawing --export-latex --export-latex gerlach-schottische002.svg 
	inkscape --export-filename=gerlach-schottische003.pdf --export-area-drawing --export-latex --export-latex gerlach-schottische003.svg 
	inkscape --export-filename=gerlach-schottische004.pdf --export-area-drawing --export-latex --export-latex gerlach-schottische004.svg 
	
##	- line 57: add escapes ("\") before "_" (2x); and \url{---} for URL

	sed -i.OLD '/http/s/_/\\_/g' gerlach-schottische001.pdf_tex
	sed -i.OLD 's/\[from http/\\scriptsize\[from \\url{http/g' gerlach-schottische001.pdf_tex
	sed -i.OLD 's/Gustav)/Gustav)}/g' gerlach-schottische001.pdf_tex
	sed -i 's/\\textbf{= 70/\\textbf{\\footnotesize = 70/g' gerlach-schottische001.pdf_tex
	sed -i 's/\\textbf{= 80/\\textbf{\\footnotesize = 80/g' gerlach-schottische001.pdf_tex

##	- add "\scriptsize" before every "3-plet"  
##	- change font for measure numbers from italics (it) to typewriter (tt) 

	sed -i.OLD 's/\[t\]{c}\\textit{3}/\[t\]{c}\\textit{\\scriptsize 3}/g' gerlach-schottische00*.pdf_tex
	sed -i.OLD 's/\[t\]{l}\\textit{/\[t\]{c}\\texttt{\\footnotesize /g' gerlach-schottische00*.pdf_tex

# Generate the PDF

	pdflatex -synctex=1 -interaction=nonstopmode -shell-escape mdgBookSVG6v1.tex
	bibtex mdgBookSVG6v1.aux
	pdflatex -synctex=1 -interaction=nonstopmode -shell-escape mdgBookSVG6v1.tex
	pdflatex -synctex=1 -interaction=nonstopmode -shell-escape mdgBookSVG6v1.tex
	
###
##
#
